"""Scan every experiments/yolo_attack/*/**/args.json and build a single
human-readable manifest: which dataset each patch was trained on, with what
hyperparameters, and where the final patch file lives.

The run folder naming (timestamps, "run01", "abl/geom_tv5", ...) has become
opaque over the course of the thesis -- this rebuilds the missing "how was
this patch trained" index from the args.json that train.py already writes
next to every patch_final.pt.

Usage on Vortex:
    python src/yolo_chroma_attack/build_run_manifest.py \\
        --root experiments/yolo_attack \\
        --out experiments/yolo_attack/MANIFEST.md
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path


def find_runs(root: Path):
    """A "run" is any directory containing an args.json + patch_final.pt."""
    for args_path in sorted(root.rglob("args.json")):
        run_dir = args_path.parent
        patch_path = run_dir / "patch_final.pt"
        yield run_dir, args_path, patch_path


def load_train_log_tail(run_dir: Path, n: int = 3) -> list[str]:
    log_path = run_dir / "train.log"
    if not log_path.exists():
        return []
    lines = log_path.read_text(errors="replace").splitlines()
    # keep only "[ep ..." lines, last n
    ep_lines = [l for l in lines if l.strip().startswith("[ep")]
    return ep_lines[-n:]


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--root", type=Path, default=Path("experiments/yolo_attack"))
    p.add_argument("--out", type=Path, default=Path("experiments/yolo_attack/MANIFEST.md"))
    args = p.parse_args()

    runs = list(find_runs(args.root))
    print(f"found {len(runs)} runs with args.json")

    lines = [
        "# Patch training run manifest",
        "",
        f"Auto-generated by build_run_manifest.py — {len(runs)} runs found.",
        "Do not hand-edit; re-run the script after new training runs.",
        "",
    ]

    # newest first (by args.json mtime)
    runs.sort(key=lambda t: t[1].stat().st_mtime, reverse=True)

    for run_dir, args_path, patch_path in runs:
        try:
            cfg = json.loads(args_path.read_text())
        except Exception as e:
            lines.append(f"## {run_dir}\n\nCORRUPT args.json: {e}\n")
            continue

        has_patch = patch_path.exists()
        tail = load_train_log_tail(run_dir)

        lines.append(f"## `{run_dir}`")
        lines.append("")
        lines.append(f"- **patch_final.pt**: {'present' if has_patch else 'MISSING'}")
        lines.append(f"- **dataset (run_dir)**: `{cfg.get('run_dir', '?')}`")
        lines.append(f"- **yolo_weights**: {cfg.get('yolo_weights', '?')}  "
                     f"**epochs**: {cfg.get('epochs', '?')}  "
                     f"**batch**: {cfg.get('batch_size', '?')}  "
                     f"**lr**: {cfg.get('lr', '?')}")
        lines.append(f"- **topk**: {cfg.get('topk', '?')}  "
                     f"**margin_tau**: {cfg.get('margin_tau', '?')}  "
                     f"**geom_eot**: {cfg.get('geom_eot', '?')}  "
                     f"**tv_weight**: {cfg.get('tv_weight', '?')}")
        if tail:
            lines.append(f"- **last log line**: `{tail[-1].strip()}`")
        lines.append("")

    args.out.write_text("\n".join(lines))
    print(f"wrote {args.out}")


if __name__ == "__main__":
    main()
